name: Docker Image on Push

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.2
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker login
        run: | 
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin  
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64,linux/arm/v6\
            -o type=registry \
            -t tknapp/google-calendar-copier:devel \
            $DEVEL \
            .
